import { Context, Session } from 'koishi';
import { FileManager } from './file-manager';
import { Config } from './config';
import { PluginLogger } from './logger';
export declare class MessageHandler {
    private ctx;
    private config;
    private fileManager;
    private logger;
    private utils;
    private correctChannelIds;
    private scheduledTasks;
    private channelRefreshInFlight;
    private lastChannelRefreshAt;
    private readonly CHANNEL_REFRESH_TTL_MS;
    constructor(ctx: Context, config: Config, fileManager: FileManager, logger: PluginLogger);
    /** 广播带 authority：启用 auth 插件后未登录的客户端收不到聊天内容 */
    private broadcast;
    private isAtBotMessage;
    private stripLeadingAtSelf;
    recordUserMessage(session: Session, timestamp: number): void;
    recordBotMessage(session: Session, timestamp: number): void;
    recordGroupMemberEvent(session: Session, kind: 'added' | 'removed'): void;
    private processGroupMemberEvent;
    recordJoinRequestEvent(session: Session): void;
    private processJoinRequestEvent;
    setCorrectChannelId(selfId: string, channelId: string): void;
    getCorrectChannelId(selfId: string): string | undefined;
    private isRawIdName;
    private resolveBotName;
    private resolveBotAvatar;
    updateBotInfoToFile(session: Session): void;
    updateChannelInfoToFile(session: Session): string;
    downloadAndCacheMedia(url: string, type: 'image' | 'media' | 'avatar' | 'audio', prefetchedBuffer?: Buffer): Promise<string>;
    private toMediaUrl;
    getCachedMediaUrl(url: string, type: 'image' | 'media' | 'avatar' | 'audio'): Promise<string | null>;
    private findCachedFile;
    private detectAudioFormat;
    private guessMediaTypeByUrl;
    private getPreferredMediaExtension;
    private isPlayableAudioBuffer;
    private transcodeAudioToMp3;
    private transcodeRawBufferToMp3;
    private processMediaElementsAsync;
    private processUserMessage;
    private processBotMessage;
    stripFaceElements(elements: any[]): any[];
    dispose(): void;
    private scheduleTask;
    private shouldRefreshChannelInfo;
    private resolveBotGroupState;
    /** 根据查询群禁言状态的结果，判断群级（全员）禁言当前是否生效 */
    computeGlobalMuted(setting: any): boolean;
    isNotGroupMemberError(error: any): boolean;
    private refreshChannelInfo;
    private resolveGuildName;
    private buildChannelName;
    private processMediaElements;
    private guessMediaTypeForElement;
    private fileExists;
}
